version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nlreturn
    - noctx
    - nolintlint
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 150
    goconst:
      min-occurrences: 5
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 80
      tab-width: 4
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - goconst
        path: _test\.go
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - lll
        source: "`json:"
      - linters:
          - lll
        source: "`yaml:"
      - path: (.+)\.go$
        text: Using the variable on range scope `tt` in function literal
      - path: (.+)\.go$
        text: Using the variable on range scope `tc` in function literal
    paths:
      - builds
      - sources
      - tarballs
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - builds
      - sources
      - tarballs
      - third_party$
      - builtin$
      - examples$
