# frozen_string_literal: true

brew 'coreutils'
brew 'curl'
brew 'expat'
brew 'gmp'
brew 'gnu-sed'
brew 'gnutls'
brew 'jansson'
brew 'libffi'
brew 'libiconv'
brew 'librsvg'
brew 'libtasn1'
brew 'libunistring'
brew 'libxml2'
brew 'little-cms2'
brew 'mailutils'
brew 'make'
brew 'ncurses'
brew 'nettle'
brew 'pkg-config'
brew 'texinfo'
brew 'zlib'
