#! /usr/bin/env bash
set -e

brewdir="$(brew --prefix)"
formula="${brewdir}/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb"

if [ ! -f "$formula" ]; then
  echo "ERROR: ${formula} does not exist." 1>&2
  exit 1
fi

gnubins=(
  "${brewdir}/opt/coreutils/libexec/gnubin"
  "${brewdir}/opt/make/libexec/gnubin"
  "${brewdir}/opt/gnu-sed/libexec/gnubin"
)

for gnubin in "${gnubins[@]}"; do
  if [ -d "$gnubin" ]; then
    export PATH="${gnubin}:$PATH"
  fi
done

cp "$formula" ./Formula/

patch -f -p1 -i ./Formula/gcc.rb.patch
brew install ./Formula/gcc.rb --build-from-source --force
